config/routes.rb
Rails.application.routes.draw do
  root to: 'books#top'

  get 'users/index'
  get 'users/show', to: 'users#show', as: 'user_show'
  get 'users/new'
  post 'users', to: 'users#create'
  get 'users/login_name', to: 'users#login_name'
  post 'login', to: 'users#login'
  get 'users/logout'
  # get 'users/:id', to: 'users#login', as: 'user_login'

  get 'books/top'
  get 'books/index'
  get 'books/show/:id', to: 'books#show', as: 'book_show'
  get 'books/new', to: 'books#new'
  get 'books/login_owner', to: 'books#login_owner'
  post 'login_owner_check', to: 'books#login_owner_check'
  get 'books/owner'
  post 'books', to: 'books#create'
  delete 'books/delete/:id', to: 'books#destroy', as: 'book_delete'
  get 'books/rend/:id', to: 'books#rend', as: 'book_rend'

  get 'lentals/rent/:id', to: 'lentals#rent', as: 'lentals_rent'
  get 'lentals/return/:id', to: 'lentals#return', as: 'lentals_return'
  get 'lentals/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/lental.rb
class Lental < ApplicationRecord

  def book
    Book.find(self.book_id)
  end

end

app/models/user.rb
class User < ApplicationRecord

  require 'users_controller.rb'

  scope :get_login_user, -> { find_by(login: true) }

  def get_rental_books
    # @user = User.find_by(login: true)
    @lentals = Lental.where('user_id = ? and book_id > ?', @user.id, 0)
    @lentals == [] ? @books = 0  : @books = Book.find(@lentals.pluck(:book_id))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
    @books = Book.all
  end

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new  
  end

  def login_owner
  end

  def login_owner_check
    if params[:owner][:name] == '管理者' && params[:owner][:password] == '123456'
      redirect_to action: 'owner'
    else
      redirect_to action: 'login_owner'
    end 
  end

  def owner
    @books = Book.all    
  end

  def create
    @book = Book.create(book_params)
    redirect_to action: 'owner'
  end

  def update
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to action: 'owner'
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :date_of_issue , :number, :summary)
  end
  
end

app/controllers/lentals_controller.rb
class LentalsController < ApplicationController

  def rent
    @book = Book.find(params[:id])
    @user = User.find_by(login: true)
    if Lental.find_by(user_id: @user.id, book_id: 0) == nil
      redirect_to user_show_path, notice: '貸出数が最大です'
    else
      @lental = Lental.find_by(user_id: @user.id, book_id: 0)
      @lental.book_id = @book.id
      @lental.save
      @book.number -= 1
      @book.save
      redirect_to user_show_path
    end   
  end

  def return
    @book = Book.find(params[:id])
    @user = User.find_by(login: true)
    @lental = Lental.find_by(user_id: @user.id, book_id: @book.id)
    @lental.book_id = 0
    @lental.save
    @book.number += 1
    @book.save
    redirect_to controller: 'users', action: 'show'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'user.rb'

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(login: true)
    @lentals = Lental.where('user_id = ? and book_id > ?', @user.id, 0)
    @lentals == [] ? @books = 0  : @books = Book.find(@lentals.pluck(:book_id))
    # User.find_by(login: true).get_rental_books
  end

  def new
  end

  def create    
    user = User.create(user_params)
    3.times do
      Lental.create(user_id: user.id, book_id: 0)
    end
    redirect_to action: 'login_name'
  end

  def login_name
    @user = params[:name]
  end

  def login
    User.update_all(login: false)
    @user = User.find_by(name: params[:user][:name])
    @user.login = true
    @user.save
    redirect_to controller: 'books', action: 'top'
  end

  def logout
    User.update_all(login: false)
    redirect_to controller: 'books', action: 'top'
  end


  private

  def user_params
    params.require(:user).permit(:name, :address)
  end

end


    # render plain: params[:user].inspect

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lentals_helper.rb
module LentalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.haml
%h2 書籍一覧
%table{border: 1}
  %tr
    %th タイトル
    %th 著者名
    %th 分類
    %th 在架数
    %th user id
    %th 
  - @books.each do |book|
    %tr
      %td= link_to book.title, book_show_path(book)
      / %td= link_to book.name, "books/#{book.id}"
      %td= book.author
      %td= book.genre
      %td= book.number
      %td= book.user_id
      -if book.number > 0
        %td= link_to book.rend, lentals_rent_path(book)
      -else
        %td= ''

app/views/books/login_owner.html.haml
%h2 管理者ログイン

= form_for :owner, url: login_owner_check_path do |f|
  %p= f.label :name
  = f.text_field :name
  %p= f.label :password
  = f.password_field :password
  %p= f.submit 'Login'

app/views/books/new.html.haml
= form_for Book.new do |f|
  %p= f.label :title
  = f.text_field :title
  %p= f.label :author
  = f.text_field :author
  %p= f.label :genre
  = f.text_field :genre
  %p= f.label :date_of_issue
  = f.text_field :date_of_issue
  %p= f.label :number_of_books
  = f.text_field :number
  %p= f.label :summary
  = f.text_area :summary
  %p= f.submit '新規登録'

app/views/books/owner.html.haml
%h2 管理者のページ
= button_to '書籍登録', {controller: 'books', action: 'new'}, {method: :get}

%h2 書籍一覧
%table{border: 1}
  %tr
    %th タイトル
    %th 著者名
    %th 分類
    %th 在架数
    %th 
  - @books.each do |book|
    %tr
      %td= link_to book.title, book_show_path(book)
      / %td= link_to book.name, "books/#{book.id}"
      %td= book.author
      %td= book.genre
      %td= book.number
      %td= link_to '削除', book_delete_path(book), method: :delete, data: {confirm: '削除しますか？'}

app/views/books/show.html.haml
%h2 書籍詳細
%table{border: 1}
  %tr
    %td タイトル
    %td= "#{@book.id}" + '.  ' + @book.title
  %tr
    %td 著者名
    %td= @book.author
  %tr
    %td 分類
    %td= @book.genre
  %tr
    %td 内容
    %td= @book.summary

%p= link_to '戻る', books_index_path(@book)

app/views/books/top.html.haml
%h2 書籍一覧
%table{border: 1}
  %tr
    %th タイトル
    %th 著者名
    %th 分類
    %th 在架数
  - @books.each do |book|
    %tr
      %td= link_to book.title, book_show_path(book)
      / %td= link_to book.name, "books/#{book.id}"
      %td= book.author
      %td= book.genre
      %td= book.number

app/views/books/update.html.haml
%h1 Books#update
%p Find me in app/views/books/update.html.erb

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WebLibraray
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      %header
        / %img.header{src: '/image1.png', width: 40}
        %h1 WEB Library
        %ul
          - if User.find_by(login: true).nil?
            %li= link_to 'TOP', books_top_path(@book)
          - else
            %li= link_to 'TOP', books_index_path(@user)

          %li= link_to 'ログイン', users_login_name_path(@user)

          - if User.find_by(login: true).nil?
            %li= link_to '貸出', users_login_name_path(@user)
          - else
            %li= link_to '貸出', books_index_path(@user)

          - if User.find_by(login: true).nil?
            %li= link_to '利用者ページ', users_login_name_path(@user)
          - else
            %li= link_to '利用者ページ', user_show_path(@user)

          %li= link_to '管理者ページ', books_login_owner_path(@book)

      = yield

app/views/users/index.html.haml
%h2 利用者 一覧
%table{border: 1}
  %tr
    %th ユーザー名
    %th 住所
    %th ログイン
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.address
      %td= user.login
      %td= user.rend1
      %td= user.rend2
      %td= user.rend3

app/views/users/login.html.haml
%h2 利用者ログイン

= form_for :user,url: login_path do |f|
  = f.label :name
  = f.text_field :name
  = f.submit 'Login', data: {confirm: 'ログインしますか？'}

= button_to '新規登録', {controller: 'users', action: 'new'}, {method: :get}



/ = form_for :user,url: login_path do |f|
/   = f.label :name
/   = f.text_field :name
/   = f.submit

app/views/users/login_name.html.haml
%h2 利用者ログイン

= form_for :user,url: login_path do |f|
  = f.label :name
  = f.text_field :name
  = f.submit 'Login', data: {confirm: 'ログインしますか？'}

= button_to '新規登録', {controller: 'users', action: 'new'}, {method: :get}

app/views/users/new.html.haml
%h2 利用者新規登録

= form_for User.new do |f|
  %p= f.label :name
  = f.text_field :name
  %p= f.label :address
  = f.text_field :address
  %p= f.submit '登録'

app/views/users/show.html.haml
%h2 利用者のページ

%p= '名　前：' + @user.name
%p= '住　所：' + @user.address
= button_to 'ログアウト', {controller: 'users', action: 'logout'}, {method: :get}
%p

- if @books == 0
  %h4 現在、貸出図書はありません
- else
  %table{border: 1}
    %tr
      %th タイトル
      %th 著者名
      %th 分類
      %th 返却期限
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.author
        %td= book.genre
        - d = @lentals.find_by(book_id: book.id).updated_at + 14.days
        %td= d.strftime('%Y-%m-%d')
        %td= link_to '返却', lentals_return_path(book) 

= notice